"""
Conversational AI endpoints — the "Avatar" layer.

Design principle (privacy-first, per hackathon architecture decision):
Raw user financial data NEVER goes directly to the LLM. Only anonymized,
pre-processed insights (generated by the local analysis layer in
services/insights_engine.py) are passed into the prompt context.
"""

from fastapi import APIRouter
from app.schemas.chat import ChatRequest, ChatResponse

router = APIRouter()


@router.post("/", response_model=ChatResponse)
def chat_with_advisor(request: ChatRequest):
    """
    Takes a user message + anonymized financial insights,
    returns a conversational wealth-advisory response.

    TODO:
    - Pull anonymized insights for the user (from insights_engine)
    - Build prompt with insights + user message (no raw PII)
    - Call LLM (Claude API) for the response
    - Return conversational reply
    """
    return ChatResponse(
        reply="[stub] Avatar response will go here — LLM integration pending.",
        session_id=request.session_id,
    )
